"""changed year to string

Revision ID: 1e1560bcc541
Revises: 2dbd5fce4814
Create Date: 2022-12-06 15:18:45.067769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1560bcc541'
down_revision = '2dbd5fce4814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
